### ISSUE TITLE
Scale bar responds to mouse clicks

### ISSUE THREAD

**Issue by bgilbert** [NIST-ISG/OpenSeadragonScalebar#2]
Mouse clicks on the scale bar are caught by the bar itself, and not passed through to the viewer.  This interferes with navigation if the user happens to perform a click-to-zoom action, or to start a drag-to-pan gesture, over the scale bar.  (This is particularly surprising in microscopy mode with no background color.)

**Comment by avandecreme** [comment]
An easy fix seems to set the CSS property pointer-events: none to the scalebar:
http://stackoverflow.com/questions/1009753/pass-mouse-events-through-absolutely-positioned-element
However, it won't work with IE<11: http://caniuse.com/#feat=pointer-events

Maybe @msalsbery knows a better way?

**Comment by msalsbery** [comment]
I'll take a look...I've never played with this plugin :)

**Comment by avandecreme** [comment]
Thanks!

**Comment by msalsbery** [comment]
Just quickly looking at the code, I don't see an element that would prevent bubbling.

I would call this on the div however:
```javascript
$.setElementTouchActionNone(this.divElt);
```
But that just affects touch.

I'll need to throw together a test page to dig deeper...

**Comment by avandecreme** [comment]
Ha yeah, didn't event think of the touch events, thanks.

You can get a test page just by checking out the gh-pages branch.

**Comment by avandecreme** [comment]
Ok I made the easy fix with the CSS property. So not working on IE<11.
If anyone has a fix for old IEs, let me know :)
