### ISSUE TITLE
Bug OSD 2.0 Viewport.viewportToImageZoom not compatible with multi-image.

### ISSUE THREAD

**Issue by hadleyfellows** [NIST-ISG/OpenSeadragonScalebar#4]
When refreshing the the scalebar using the refresh() method it requires:
     "var zoom = this.viewportToImageZoom(viewport.getZoom(true));"
Viewport.viewportToImageZoom(viewportZoom) is not compatible with multi-image OSD instances.

I do have one solution, which is to pull the depreciated methods from Viewport into openseadragon-scalebar.js and update the variables to support multiple images. I have a possible solution that worked for me. Let me know if you would like me to submit it.

Any suggestions or alternatives would be great.

Thanks,

Hado Longfello

**Comment by avandecreme** [comment]
Yes I am aware that the plugin is not working very well with multiple images.

For my use case, when I have multiple images, they are usually laid out in a way that the plugin is actually working regardless of the warning. They are 2 cases:
-the second image may just be segmentation of the main one, so they have the same dimensions and are displayed on top of each other with some transparency.
-the second image is a higher resolution of part of the main one, but the way they are laid out in the world keeps the same pixels/meter

Are you in one of these 2 cases? If not, how should the scalebar be displayed? One scalebar per image?

Pinging @iangilman for reference :)

**Comment by hadleyfellows** [comment]
Great point. I am using the same layout for multiple images:

"-the second image may just be segmentation of the main one, so they have the same dimensions and are displayed on top of each other with some transparency."

In my case I am using multiple viewports as well which affects the world.items order but not the pixels/meter. I am using the tileSources[<current page>] instead. I see that this is working without the fix I used, but does display errors.

Thanks for such a quick response.

**Comment by avandecreme** [comment]
Ok I added basic support.
One can now specify which world item the pixels/meter is referring to with the referenceItemIdx option.

Let me know if you have any issue with it.

**Comment by hadleyfellows** [comment]
Great! Thanks!
I'll check it out.
