### ISSUE TITLE
canvas with both image and the scalebar

### ISSUE THREAD

**Issue by meihuisu** [NIST-ISG/OpenSeadragonScalebar#6]
With existing getAsCanvas(), it was simple to make a function that merge the underlying image with
the matching scalebar. Could I send this in?

**Comment by avandecreme** [comment]
Sure!
However, we are in the process of moving this repository to https://github.com/usnistgov/OpenSeadragonScalebar
So please, submit the PR there.

**Comment by meihuisu** [comment]
thanks. it worked.
