### ISSUE TITLE
Scalebar floats if rotation applied

### ISSUE THREAD

**Issue by boskar** [NIST-ISG/OpenSeadragonScalebar#7]
See examples here: 

http://www.lekarski.katowice.pl/notworking/rotate90.php?szkielko_guid=40D0E84BCE094A619BFBC3066BCBABAE

http://www.lekarski.katowice.pl/notworking/rotate.php?szkielko_guid=40D0E84BCE094A619BFBC3066BCBABAE

I don't know to what we should anchor to make it work correctly : (

**Comment by avandecreme** [comment]
Thanks for reporting.
One workaround that you can use right now is to set `stayInsideImage` to false.

We are in the process of moving this repository to https://github.com/NIST-ISG/OpenSeadragonScalebar so I opened an issue for this there: https://github.com/usnistgov/OpenSeadragonScalebar/issues/2
